[env:esp32]
platform        = espressif32
board           = esp32dev
framework       = espidf
board_build.flash_size = 4MB
monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
    -Wno-unused-variable
    -Wno-unused-function
